name: "Validate PR Metadata"
description: "Validates CodeYourFuture trainee pull request metadata"
inputs:
  GITHUB_TOKEN:
    description: GitHub Token to use, probably literally ${{ secrets.GITHUB_TOKEN }}
    # required: true
    default: ${{ secrets.GITHUB_TOKEN }}
runs:
  steps:
    - uses: actions/checkout@v4
    - name: Download Validator
      run: curl --fail https://api.github.com/repos/CodeYourFuture/trainee-tracker/releases/latest | jq '.assets[] | select(.name | startswith("pr-metadata-validator-musl-")).browser_download_url' | xargs curl --fail -L -o /tmp/pr-metadata-validator && chmod 0755 /tmp/pr-metadata-validator
      shell: bash
    - name: Validate PR Metadata
      run: /tmp/pr-metadata-validator ${{ github.event.pull_request.html_url }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
